---
version: 2
project_name: aqua

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*

builds:
  - binary: aqua
    main: cmd/aqua/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/aquaproj/aqua/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/aquaproj/aqua/compare/{{.PreviousTag}}...{{.Tag}}

sboms:
  - id: default
    disable: false

homebrew_casks:
  - repository:
      owner: aquaproj
      name: homebrew-aqua
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/aquaproj/aqua
    description: |
      Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
    license: MIT
    skip_upload: true
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aqua"]
          end

scoops:
  - description: |
      Declarative CLI Version manager written in Go.
      Support Lazy Install, Registry, and continuous update by Renovate.
      CLI version is switched seamlessly
    license: MIT
    skip_upload: true
    repository:
      owner: aquaproj
      name: scoop-bucket

winget:
  - publisher: aquaproj
    short_description: Declarative CLI Version manager written in Go
    license: mit

    # Publisher URL.
    #
    # Templates: allowed
    # publisher_url: https://goreleaser.com

    publisher_support_url: https://github.com/aquaproj/aqua/discussions

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: v1
    # goamd64: v1

    # URL which is determined by the given Token (github, gitlab or gitea).
    #
    # Default depends on the client.
    # Templates: allowed
    url_template: "https://github.com/aquaproj/aqua/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # commit_author:
    #   name: Shunsuke Suzuki
    #   email: suzuki.shunsuke.1989@gmail.com

    # The project name and current git tag are used in the format string.
    #
    # Templates: allowed
    # commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"

    # Path for the file inside the repository.
    #
    # Default: manifests/<lowercased first char of publisher>/<publisher>/<version>
    # path: manifests/g/goreleaser/1.19

    homepage: https://github.com/aquaproj/aqua

    # Your app's long description.
    #
    # Templates: allowed
    description: |
      Declarative CLI Version manager written in Go.
      Support Lazy Install, Registry, and continuous update by Renovate.
      CLI version is switched seamlessly

    license_url: https://github.com/aquaproj/aqua/blob/main/LICENSE

    # Copyright.
    #
    # Templates: allowed
    # copyright: ""

    # Copyright URL.
    #
    # Templates: allowed
    # copyright_url: ""

    # Setting this will prevent goreleaser to actually try to commit the updated
    # package - instead, it will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    #
    # If set to auto, the release will not be uploaded to the repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    #
    # Templates: allowed
    skip_upload: true

    # Release notes.
    #
    # If you want to use the release notes generated by GoReleaser, use
    # `{{.Changelog}}` as the value.
    #
    # Templates: allowed
    # release_notes: "{{.Changelog}}"

    # Release notes URL.
    #
    # Templates: allowed
    release_notes_url: https://github.com/aquaproj/aqua/releases/tag/{{.Tag}}

    # Tags.
    # tags:
    #   -

    # Repository to push the generated files to.
    repository:
      owner: suzuki-shunsuke
      # owner: mini-core
      name: winget-pkgs

      # Optionally a branch can be provided.
      #
      # Default: default repository branch
      # Templates: allowed
      branch: "aqua-{{.Version}}"

      # Sets up pull request creation instead of just pushing to the given branch.
      # Make sure the 'branch' property is different from base before enabling
      # it.
      #
      # Since: v1.17
      pull_request:
        # Whether to enable it or not.
        enabled: true

        # Whether to open the PR as a draft or not.
        #
        # Since: v1.19
        draft: true

        # Base can also be another repository, in which case the owner and name
        # above will be used as HEAD, allowing cross-repository pull requests.
        #
        # Since: v1.19
        base:
          owner: microsoft
          # owner: mini-core
          name: winget-pkgs
