title: Feature Request
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: Please use the issue template instead

        We keep this discussion category only for old discussions.

        [Please create an issue using the issue template](https://github.com/aquaproj/aqua/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml).
  - type: checkboxes
    attributes:
      label: .
      options:
        - label: ..
