title: Support Request
body:
  - type: textarea
    id: aqua-info
    attributes:
      label: aqua info
      description: |
        Please use the latest version.
        Please run `aqua info` command and paste the result.
        `aqua info` requires `aqua >= v2.10.0`.
        If you use `aqua < v2.10.0`, please run `aqua -v` and write OS and CPU architecture instead.
        If you checked multiple versions, please write the result too.
        e.g. This issue occurs with aqua v2.5.0 too, but doesn't occur with aqua v2.4.0.
      value: |
        ```console
        $ aqua info

        ```

        #### aqua < v2.10.0

        ```console
        $ aqua -v

        ```

        OS (Windows, Linux, macOS, etc):
        CPU Architecture (amd64, arm64, etc):

    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      value:
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        aqua.yaml should be not partial but complete configuration.
        Please remove unneeded configuration to reproduce the issue.
      value: |
        aqua.yaml

        ```yaml

        ```

        Other related code such as local Registry

        ```

        ```

        Executed command and output

        ```console
        $ 
        ```
    validations:
      required: true
  - type: textarea
    id: debug-output
    attributes:
      label: Debug output
      description: Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.
      value: |
        ```console
        $ 
        ```
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      value:
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      value:
    validations:
      required: true
  - type: textarea
    id: important-factoid
    attributes:
      label: Important Factoids
      value:
    validations:
      required: false
  - type: textarea
    id: reference
    attributes:
      label: Reference
      value: |
        *
    validations:
      required: false
