#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

help=$(aqua help-all)

echo "---
sidebar_position: 400
---

# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$help
" > docs/reference/usage.md
