#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

command_console() {
  echo '```console'
  echo "$ $*"
  eval "$@"
  echo '```'
}

echo "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$(command_console aqua help)

## aqua install

$(command_console aqua help install)

## aqua exec

$(command_console aqua help exec)

## aqua generate

$(command_console aqua help generate)

## aqua list

$(command_console aqua help list)"
