---
name: actionlint
on: pull_request
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/actionlint-action@bbce1e825be8286c27e00c3f6c42adccf5955fba # v0.2.1
