name: Close issue

on:
  issues:
    types: [opened]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'suzuki-shunsuke'
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/issue-close-lock-action@231aefd9a92cddfd2eb51e60965e9468f3d592bd # v0.1.0
        with:
          issue_number: ${{github.event.issue.number}}
          message: |
            # Please create a GitHub Discussion instead of this issue

            https://github.com/orgs/aquaproj/discussions

            Only maintainers can create new Issues. If needed, a maintainer will create an Issue after your Discussion been triaged and confirmed.

            This Issue will now be closed and locked. This way we keep Issues actionable, and free of duplicates or wrong bug reports.

            Thanks
