---
name: Create Status Check
on:
  workflow_run:
    workflows: [test] # pull_request workflow name
    types:
      - completed
jobs:
  create-status-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      statuses: write # To update commit statuses
    steps:
      - uses: suzuki-shunsuke/status-check-workflow-run-action@79471ff024007dbc192e6ce0576f71960b1c144d # v0.1.1
