---
name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - website/**
      - .github/workflows/deploy_doc.yaml
permissions: {}
jobs:
  deploy-doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    with:
      issue_number: 4095
    permissions:
      contents: write
      issues: write
