---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@1cf29d7b17983b901021799b87a55d357cfff790 # v9.0.0
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    with:
      go-version-file: go.mod
      aqua_policy_allow: true
      aqua_version: v2.60.1
    permissions:
      contents: write
      id-token: write
      actions: read
      attestations: write
