---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@b2ecf54e35aca9e9689e761f5bd6d1ad9542a8cf # v8.0.0
    with:
      go-version-file: go.mod
      aqua_policy_allow: true
      aqua_version: v2.59.0
    permissions:
      contents: write
      id-token: write
      actions: read
      attestations: write
