---
name: test GoReleaser
on: workflow_call
jobs:
  test-goreleaser:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.63.0
      - run: goreleaser check
      # Build is too slow for a test
      # - run: goreleaser release --snapshot
