---
name: status-check
on: workflow_call
jobs:
  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: exit 1
