---
name: test-docker-prebuilt
on: workflow_call
jobs:
  test-docker:
    # Test Dockerfile
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - run: docker build -t aquaproj-aqua-dev -f Dockerfile-prebuilt .
