---
name: test-docker-prebuilt
on: workflow_call
jobs:
  test-docker:
    # Test Dockerfile
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: docker build -t aquaproj-aqua-dev -f Dockerfile-prebuilt .
