---
name: test-docker-prebuilt
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
jobs:
  test-docker:
    # Test Dockerfile
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - run: docker build --target prebuilt .

  test-docker-build:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: flatt-security/setup-takumi-guard-golang@2e3c7c40b538cd68b2ac483def12982ebc8bc02e # v1
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}

      - run: |
          go install \
            -ldflags "-X main.version=v2.48.2-local -X main.commit=$sha -X main.date=$(date +"%Y-%m-%dT%H:%M:%SZ%:z" | tr -d '+')" \
            ./cmd/aqua
      - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
      - run: aqua i -l
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - run: mkdir -p dist
      - run: cp ~/go/bin/aqua dist/aqua-docker
      - run: docker build -t build .
