---
name: test-docker-prebuilt
on: workflow_call
jobs:
  test-docker:
    # Test Dockerfile
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: docker build -t aquaproj-aqua-dev -f Dockerfile-prebuilt .
