---
name: typos
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.46.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: typos
