---
name: typos
on: workflow_call
permissions: {}
env:
  AQUA_LOG_COLOR: always
jobs:
  typos:
    timeout-minutes: 10
    runs-on: ubuntu-26.04
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.63.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: typos
