---
name: test (workflow_call)
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      test-docker: ${{steps.changes.outputs.test-docker}}
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            test-docker:
              - Dockerfile
              - .github/workflows/wc-test-docker.yaml

  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@98ab396ba72f7b47f7e22aca7346b6e1d7ae4deb # v6.0.0
    with:
      aqua_version: v2.61.0
      golangci-lint-timeout: 120s
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      pull-requests: write
      contents: read
      id-token: write

  test-goreleaser:
    uses: ./.github/workflows/test-goreleaser.yaml
    needs: path-filter
    permissions: {}

  test-docker:
    uses: ./.github/workflows/wc-test-docker.yaml
    needs: path-filter
    if: needs.path-filter.outputs.test-docker == 'true'
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: read
      id-token: write

  integration-test:
    uses: ./.github/workflows/wc-integration-test.yaml
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: read
      id-token: write

  test_doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: write
      issues: write
      id-token: write

  typos:
    uses: ./.github/workflows/workflow_call_typos.yaml
    permissions: {}
